apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
      - name: python-app
        image: {{ .Values.deployment.image.repositories }}:{{ .Values.deployment.image.tag }}
        ports:
        - containerPort: {{ .Values.deployment.ports.containerPort }}
      imagePullSecrets:
      - name: {{ .Values.deployment.imagePullSecrets.name }}
      volumes:
      - name: {{ .Values.deployment.volumes.name }}
        configMap:
          name: {{ .Values.deployment.volumes.configMap.name }}
